//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPROJECTMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EgitimlerTbl
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="Bu alaný boþ geçemezsiniz")]
        public string Title { get; set; }
        public string Subtitle1 { get; set; }
        public string Subtitle2 { get; set; }
        public string AGNO { get; set; }
        public string Date { get; set; }
    }
}
