//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPROJECTMVC.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCvEntities : DbContext
    {
        public DbCvEntities()
            : base("name=DbCvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTbl> AdminTbl { get; set; }
        public virtual DbSet<DeneyimlerTbl> DeneyimlerTbl { get; set; }
        public virtual DbSet<EgitimlerTbl> EgitimlerTbl { get; set; }
        public virtual DbSet<HakkımdaTbl> HakkımdaTbl { get; set; }
        public virtual DbSet<HobilerTbl> HobilerTbl { get; set; }
        public virtual DbSet<IletisimTbl> IletisimTbl { get; set; }
        public virtual DbSet<SertifikalarTbl> SertifikalarTbl { get; set; }
        public virtual DbSet<YeteneklerTbl> YeteneklerTbl { get; set; }
    }
}
