//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPROJECTMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeteneklerTbl
    {
        public int ID { get; set; }
        public string Workflow { get; set; }
        public Nullable<byte> Oran { get; set; }
    }
}
